### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by Girija17**
Task 1 completed

### CODE REVIEW

**Comment by dhairyajoshi** [comment]
create the file in the `open_source/git1` folder.

**Comment by Girija17** [comment]
Ok

**Comment by Girija17** [comment]
I have created the file in open source/git1. The files in github were
created by mistake. I have deleted those now

**Comment by Anonymous2610** [comment]
You still don't have your text file in `open_source/Git1` folder. Create that file and commit again.

**Pull request closed without merging**
