### PR TITLE
 avanindra_senapati.txt task 2 completed

### PR DESCRIPTION
**Pull request by Avanindra00**

### CODE REVIEW

**Comment by Anonymous2610** [comment]
Your branch is still behind the upstream branch.

**Comment by Avanindra00** [comment]
Bhaiya what to do then ?

**Comment by Anonymous2610** [comment]
Read again the readme.md file in `open_sourcde/Git2` folder. 
Hint: Pull changes from upstream branch (EnigmaVSSUT:main)

**Comment by Avanindra00** [comment]
bhaiya now u can check

**Pull request merged**
