### PR TITLE
web development task1 completed

### PR DESCRIPTION
**Pull request by venketeswar664**

### CODE REVIEW

**Comment by Anonymous2610** [comment]
Submit from `main` branch only

**Comment by venketeswar664** [comment]
> 

Main se hai kya tha

**Comment by venketeswar664** [comment]
> Submit from `main` branch only

Bhaiya main se hai kya tha

**Comment by Anonymous2610** [comment]
> > Submit from `main` branch only
> 
> Bhaiya main se hai kya tha

yeh kya h
`[venketeswar664](https://github.com/venketeswar664) wants to merge 1 commit into [EnigmaVSSUT:main](https://github.com/EnigmaVSSUT/Induction-2022) from [venketeswar664:patch-4](https://github.com/venketeswar664/Induction-2022/tree/patch-4)`

**Pull request closed without merging**
