### PR TITLE
task 2

### PR DESCRIPTION
**Pull request by Girija17**
task 2 completed

### CODE REVIEW

**Comment by Anonymous2610** [comment]
Pull changes from upstream branch

**Comment by Anonymous2610** [comment]
Not Done

**Comment by Anonymous2610** [comment]
Submit both Task-1 and Task-2

**Comment by Girija17** [comment]
Ok, I will do it.

**Comment by Girija17** [comment]
Should I repeat the whole process of tasks 1 and 2??

**Pull request closed without merging**
